package com.jetbrains;

//Guessing game for random numbers. 

public class GameLauncher {

    public static void main(String[] args) {
        GuessGame game = new GuessGame();
        game.startGame();
    }

}

class GuessGame {
    Player player1 = new Player();
    Player player2 = new Player();
    Player player3 = new Player();

    void startGame(){
        int guessp1, guessp2, guessp3, randomNumber;

        boolean p1isright = false;
        boolean p2isright = false;
        boolean p3isright = false;

        randomNumber = (int)(Math.random() * 10);
        System.out.println ("Random number generated by game is " + randomNumber);
        while (true) {
            player1.guess();
            player2.guess();
            player3.guess();

            guessp1 = player1.number;
            System.out.println ("Number guessed by Player1 is " + guessp1);
            guessp2 = player2.number;
            System.out.println ("Number guessed by Player2 is " + guessp2);
            guessp3 = player3.number;
            System.out.println ("Number guessed by Player3 is " + guessp3);

            if (guessp1 == randomNumber){
                p1isright = true;
            }
            if (guessp2 == randomNumber){
                p2isright = true;
            }
            if (guessp3 == randomNumber){
                p3isright = true;
            }

            if (p1isright || p2isright || p3isright) {
                System.out.println ("We have winner!");
                System.out.println ("Is Player1 guessed it right? " + p1isright);
                System.out.println ("Is Player2 guessed it right? " + p2isright);
                System.out.println ("Is Player3 guessed it right? " + p3isright);
                System.out.println ("Game is over");
                break;
            }
            else {
                System.out.println ("No one guessed it right. Players will have to try again!");
            }
        }
    }
}

class Player {
    int number;
    void guess() {
        number = (int) (Math.random()*10);
    }
}
